In [1]:
pip install pandas numpy scikit-learn boto3 sagemaker matplotlib seaborn

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (1.26.4)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.12/site-packages (1.7.2)
Requirement already satisfied: boto3 in /opt/conda/lib/python3.12/site-packages (1.43.46)

Collecting sagemaker

  Downloading sagemaker-3.19.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.9)
Requirement already satisfied: seaborn in /opt/conda/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2026.3)

Requirement already satisfied: scipy>=1.8.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.46 in /opt/conda/lib/python3.12/site-packages (from boto3) (1.43.46)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from boto3) (0.19.1)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.44.0,>=1.43.46->boto3) (1.26.20)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Collecting sagemaker-core<3.0.0,>=2.19.0 (from sagemaker)
  Downloading sagemaker_core-2.19.0-py3-none-any.whl.metadata (5.7 kB)

Collecting sagemaker-train<2.0.0,>=1.19.0 (from sagemaker)
  Downloading sagemaker_train-1.19.0-py3-none-any.whl.metadata (8.2 kB)
Collecting sagemaker-serve<2.0.0,>=1.19.0 (from sagemaker)

  Downloading sagemaker_serve-1.19.0-py3-none-any.whl.metadata (14 kB)
Collecting sagemaker-mlops<2.0.0,>=1.19.0 (from sagemaker)
  Downloading sagemaker_mlops-1.19.0-py3-none-any.whl.metadata (19 kB)

Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2.13.4)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (6.0.3)
Requirement already satisfied: jsonschema<5.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.23.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.11.0)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.0.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (6.10.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.16.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2.34.2)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (26.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (25.0)
Requirement already satisfied: protobuf<7.0.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (6.31.1)
Requirement already satisfied: smdebug_rulesconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (1.0.1)
Requirement already satisfied: schema>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.7.8)
Requirement already satisfied: omegaconf>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2.3.0)
Requirement already satisfied: cloudpickle>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.1.2)
Requirement already satisfied: paramiko>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (5.0.0)
Requirement already satisfied: tblib>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.2.2)
Requirement already satisfied: cryptography>=46.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.19.0->sagemaker) (46.0.7)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.37.0)

Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (2.20.0)
Requirement already satisfied: pyiceberg>=0.8.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (0.11.1)
Requirement already satisfied: pyarrow>=14.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (21.0.0)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (2026.6.0)
Requirement already satisfied: deepdiff in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (9.1.0)
Requirement already satisfied: mlflow in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.13.0)
Requirement already satisfied: sagemaker_schema_inference_artifacts in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.0.5)
Requirement already satisfied: pytest in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (9.1.1)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (4.69.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (5.9.8)
Requirement already satisfied: tritonclient[http] in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.41.1)
Requirement already satisfied: onnx in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.20.0)
Requirement already satisfied: onnxruntime in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.26.0)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.8.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.4.3)
Requirement already satisfied: jinja2<4.0,>=3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.1.6)
Requirement already satisfied: sagemaker-mlflow<1.0.0,>=0.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.19.0->sagemaker) (0.5.0)
Requirement already satisfied: nest_asyncio>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.19.0->sagemaker) (1.6.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.2.0)

Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<4.0,>=3.0->sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.0.3)
Requirement already satisfied: Flask-CORS<7 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (6.0.5)
Requirement already satisfied: Flask<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.1.3)
Requirement already satisfied: aiohttp<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.14.2)
Requirement already satisfied: alembic!=1.10.0,<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.18.5)
Requirement already satisfied: cachetools<8,>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (8.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.122.0)
Requirement already satisfied: docker<8,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (7.2.0)
Requirement already satisfied: fastapi<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.139.2)
Requirement already satisfied: gitpython<4,>=3.1.9 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.1.53)
Requirement already satisfied: gunicorn<27 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (23.0.0)
Requirement already satisfied: huey<4,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.6.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.43.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.43.0)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.2.2)
Requirement already satisfied: skops<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.0.51)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.5.0)
Requirement already satisfied: starlette<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.52.1)
Requirement already satisfied: uvicorn<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.51.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.24.5)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.3.12)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.12/site-packages (from cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (1.17.1)

Requirement already satisfied: google-auth~=2.0 in /opt/conda/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.56.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.4.2)

Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /opt/conda/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.64b0)
Requirement already satisfied: mlflow-skinny>=2.8 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlflow<1.0.0,>=0.0.1->sagemaker-train<2.0.0,>=1.19.0->sagemaker) (3.13.0)
Collecting prettytable>=3.9 (from skops<1->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker)

  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)

Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.5.3)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette<2->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (4.14.2)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn<1->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.16.0)

Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.14->cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.0)

Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (0.1.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf>=2.1.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (4.9.3)
Requirement already satisfied: bcrypt>=3.2 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (5.0.0)
Requirement already satisfied: invoke>=2.0 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (3.0.3)
Requirement already satisfied: pynacl>=1.5 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.19.0->sagemaker) (1.5.0)

Requirement already satisfied: wcwidth>=0.3.5 in /opt/conda/lib/python3.12/site-packages (from prettytable>=3.9->skops<1->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.8.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/conda/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.6.4)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (5.2.1)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (2026.6.0)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (1.0.4)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (0.25.0)

Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.32.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (3.6.1)
Requirement already satisfied: mpmath<1.5,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.4.1)

Requirement already satisfied: cachebox<6,>=5.2 in /opt/conda/lib/python3.12/site-packages (from deepdiff->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (5.2.3)
Requirement already satisfied: orderly-set<6,>=5.5.0 in /opt/conda/lib/python3.12/site-packages (from deepdiff->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (5.5.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /opt/conda/lib/python3.12/site-packages (from onnx->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.5.4)

Requirement already satisfied: flatbuffers in /opt/conda/lib/python3.12/site-packages (from onnxruntime->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (25.12.19)
Requirement already satisfied: iniconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.6.0)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from s3fs->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (3.8.0)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (0.13.0)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.19.0->sagemaker) (1.17.3)
Requirement already satisfied: json5>=0.9.22 in /opt/conda/lib/python3.12/site-packages (from sagemaker_schema_inference_artifacts->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (0.15.0)

Requirement already satisfied: python-rapidjson>=0.9.1 in /opt/conda/lib/python3.12/site-packages (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.23)

Collecting geventhttpclient<=2.0.2,>=1.4.4 (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker)
  Downloading geventhttpclient-2.0.2.tar.gz (73 kB)

  Installing build dependencies ... -

 \

 |

 /

 -

 done

  Getting requirements to build wheel ... -

 done

  Preparing metadata (pyproject.toml) ... -

 done

Collecting gevent>=0.13 (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker)
  Downloading gevent-26.8.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: brotli in /opt/conda/lib/python3.12/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker) (1.1.0)
Collecting zope.event (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker)

  Downloading zope_event-6.2-py3-none-any.whl.metadata (5.4 kB)

Collecting zope.interface (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.19.0->sagemaker)
  Downloading zope_interface-8.5-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (47 kB)

Downloading sagemaker-3.19.0-py3-none-any.whl (11 kB)

Downloading sagemaker_core-2.19.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.3 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.9 MB/s  0:00:00
Downloading sagemaker_mlops-1.19.0-py3-none-any.whl (223 kB)
Downloading sagemaker_serve-1.19.0-py3-none-any.whl (285 kB)

Downloading sagemaker_train-1.19.0-py3-none-any.whl (444 kB)
Downloading prettytable-3.18.0-py3-none-any.whl (37 kB)

Downloading gevent-26.8.0-cp312-cp312-manylinux_2_28_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 59.5 MB/s  0:00:00

Downloading zope_event-6.2-py3-none-any.whl (6.5 kB)
Downloading zope_interface-8.5-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (270 kB)

Building wheels for collected packages: geventhttpclient

  Building wheel for geventhttpclient (pyproject.toml) ... -

 \

 done
  Created wheel for geventhttpclient: filename=geventhttpclient-2.0.2-cp312-cp312-linux_x86_64.whl size=45232 sha256=6174fff1276b7344f13783d5d0f7959acabbc3f2508feb313335af181d01dc48
  Stored in directory: /home/sagemaker-user/.cache/pip/wheels/c1/14/27/8606138a08ae583308705ede0aa4d34ce0acb71d25ba0cd4a1
Successfully built geventhttpclient

Installing collected packages: zope.interface, zope.event, prettytable, gevent, geventhttpclient, sagemaker-core, sagemaker-train, sagemaker-serve, sagemaker-mlops, sagemaker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/10 [zope.interface]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/10 [gevent]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/10 [gevent]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/10 [gevent]

  Attempting uninstall: sagemaker-core
    Found existing installation: sagemaker-core 2.16.0
   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/10 [gevent]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

    Uninstalling sagemaker-core-2.16.0:
      Successfully uninstalled sagemaker-core-2.16.0
   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

  Attempting uninstall: sagemaker-train
    Found existing installation: sagemaker-train 1.14.0
   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

    Uninstalling sagemaker-train-1.14.0:
      Successfully uninstalled sagemaker-train-1.14.0
   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  5/10 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━  6/10 [sagemaker-train]

   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━  6/10 [sagemaker-train]

  Attempting uninstall: sagemaker-serve
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━  6/10 [sagemaker-train]

    Found existing installation: sagemaker-serve 1.12.0
    Uninstalling sagemaker-serve-1.12.0:
      Successfully uninstalled sagemaker-serve-1.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━  6/10 [sagemaker-train]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━  7/10 [sagemaker-serve]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━  7/10 [sagemaker-serve]

  Attempting uninstall: sagemaker-mlops
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━  7/10 [sagemaker-serve]

    Found existing installation: sagemaker-mlops 1.12.0
    Uninstalling sagemaker-mlops-1.12.0:
      Successfully uninstalled sagemaker-mlops-1.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━  7/10 [sagemaker-serve]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━  8/10 [sagemaker-mlops]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [sagemaker]

Successfully installed gevent-26.8.0 geventhttpclient-2.0.2 prettytable-3.18.0 sagemaker-3.19.0 sagemaker-core-2.19.0 sagemaker-mlops-1.19.0 sagemaker-serve-1.19.0 sagemaker-train-1.19.0 zope.event-6.2 zope.interface-8.5

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import boto3
import sagemaker

print("Environment ready")

Environment ready

In [6]:
import boto3
import pandas as pd

# S3 bucket and file
bucket = "chunculead"
key = "customer_churn.csv"

# Create S3 client
s3 = boto3.client("s3")

# Get the file from S3
response = s3.get_object(
    Bucket=bucket,
    Key=key
)

# Read CSV into pandas
df = pd.read_csv(response["Body"])

# Display first 5 rows
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,8270-TOKH,Female,0,No,No,58,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,36.74,2171.88,No
1,6734-ZSWK,Male,1,Yes,No,44,No,No phone service,DSL,Yes,...,Yes,No,No,No,One year,No,Electronic check,77.97,3387.37,Yes
2,6578-XUDH,Male,0,No,No,25,No,No phone service,Fiber optic,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,81.61,2067.88,No
3,9322-VUBX,Female,0,No,No,64,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,No,Electronic check,85.62,5528.86,Yes
4,7949-BUAL,Male,1,Yes,No,10,Yes,Yes,DSL,No,...,No,No,Yes,No,One year,Yes,Credit card (automatic),77.54,745.20,Yes

In [7]:
df.shape

(7043, 21)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7033 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [9]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7033.000000
mean        0.151640    35.990345       75.286761   2707.869899
std         0.358697    20.928970       23.645328   1843.941881
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000    18.000000       59.125000   1169.380000
50%         0.000000    36.000000       78.920000   2442.660000
75%         0.000000    54.000000       93.235000   4034.990000
max         1.000000    72.000000      127.000000   8789.330000

In [10]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        10
Churn                0
dtype: int64

In [11]:
df["Churn"].value_counts()

Churn
No     4768
Yes    2275
Name: count, dtype: int64